require('lazy').setup({

  { import = 'plugins' },
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} -- Use default Nerd Font icons
      or {
        -- Unicode fallback icons
        cmd = '⌘',
        config = '🛠',
        event = '📅',
        ft = '📂',
        init = '⚙',
        keys = '🗝',
        plugin = '🔌',
        runtime = '💻',
        require = '🌙',
        source = '📄',
        start = '🚀',
        task = '📌',
        lazy = '💤',
        open_folder = '📂',
        closed_folder = '📁',
        file = '📄',
        modified = '✏️',
        readonly = '🔒',
        new_file = '🆕',
        deleted = '🗑',
        git_add = '➕',
        git_remove = '➖',
        git_commit = '🔖',
        git_merge = '🔀',
        git_branch = '🌿',
        git_pull = '⬇️',
        git_push = '⬆️',
        error = '❌',
        warning = '⚠️',
        info = 'ℹ️',
        hint = '💡',
        bug = '🐛',
        breakpoint = '🔴',
        debug = '🐞',
        arrow_right = '➡️',
        arrow_left = '⬅️',
        collapse = '⏷',
        expand = '⏵',
        tab = '↹',
        lock = '🔒',
        unlock = '🔓',
        pin = '📌',
        check = '✔️',
        close = '❎',
      },
  },
})
